name: "Bug Report"
description: "File a bug report"
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: "Bug description"
      description: "Please provide a detailed description of the bug."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce the bug"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Environment details"
  - type: input
    id: os
    attributes:
      label: "Operating system version"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Browser or offline application version"
      description: "Go to a new tab and type about:version"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Sprite details"
  - type: input
    id: frames
    attributes:
      label: "Number of frames"
      placeholder: 8
    validations:
      required: true
  - type: input
    id: resolution
    attributes:
      label: "Sprite resolution"
      placeholder: 16x16
    validations:
      required: true
  - type: input
    id: session-duration
    attributes:
      label: "Session duration"
      placeholder: Five million years
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional information"
